### ISSUE TITLE
SPI support

### ISSUE THREAD

**Issue by crjp** [chschlue/raspi3-image-spec#1]
SPI seems not to be available?! No /dev/spidev.

**Comment by chschlue** [comment]
Haven't looked into SPI yet.
Will do as soon as the basic functionality is stable.
Please open this issue on upstream as well if the bug doesn't just affect this fork.

**Comment by crjp** [comment]
Problem seems that SPIDEV is not compiled into the kernel.

config-4.18.0-rc4-arm64:
```
# CONFIG_SPI_SPIDEV is not set
```

**Comment by chschlue** [comment]
True.
But also, the SPI controllers are disabled in the device tree blob.

I filed a bug report with the Debian kernel team to enable CONFIG_SPI_SPIDEV.
